spring:
  application:
    name: main-service
  cloud:
    nacos:
      discovery:
        namespace: public
        #        username: nacos
        #        password: nacos
        server-addr: localhost:8848
