server:
  port: 9999

spring:
  application:
    name: ctip-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:9090
        # 默认8719端口，键入被占用会自动从8719+1，直到找到未被占用的端口
        port: 8719
    gateway:
      discovery:
        locator:
          enabled: true
        #enabled: true #开启注册中心路由功能
      routes:  # 路由
        - id: infer-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://nacos-test # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/msb/** # 断言，路径相匹配进行路由
