server:
  port: 8001

spring:
  application:
    name: ctip-gateway-service
#  profiles:
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    gateway:
      discovery:
        locator:
          enabled: true # 开启了会自动匹配路由规则
      routes:  # 路由
        - id: infer-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://infer-service/ # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/infer/** # 断言，路径相匹配进行路由
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOriginPatterns: "*" # 不是allowedOrigins
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            maxAge: 360000 # 这次跨域检测的有效期