server:
  port: 9401

spring:

  profiles:
    active: dev

  application:
    name: ctip-auth-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/ctip?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 12
      port: 6379
      host: localhost
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

jwt:
  key: ${JWT_KEY}
  ttl: 3600000
